import greenApartmentCityViewSlide from '../img/slider-main/green-apartment-city-view.jpg';
import marshmallowStudioSlide from '../img/slider-main/marshmallow-studio.jpg';
// import greenPointApartmentSlide from '../img/slider-main/green-point-apartment.jpg';
import linerSlide from '../img/slider-main/liner.jpg';
import floraApartmentSlide from '../img/slider-main/flora-apartment.jpg';
import goodVibesOnlyApartmentSlide from '../img/slider-main/good-vibes-only-apartment.jpg';
// import happyMomentsApartmentSlide from '../img/slider-main/happy-moments-apartment.jpg';
// import skyRiverApartmentSlide from '../img/slider-main/sky-river-apartment.jpg';
import centralStreetApartmentSlide from '../img/slider-main/central-street-apartment.jpg';
// import nаturеApartmentSlide from '../img/slider-main/nаturе-араrtmеnt.jpg';
// import pinkDrеаmApartmentSlide from '../img/slider-main/pink-drеаm-араrtmеnt.jpg';
import muzaApаrtmentSlide from '../img/slider-main/muza-аpаrtment.jpg';
import artAоintApartmentSlide from '../img/slider-main/art-роint-араrtmеnt.jpg';

import { greenApartmentCityView } from "./apartSourceImg/green-apartment-city-view";
import { marshmallowStudio } from "./apartSourceImg/marshmallow-studio";
// import { greenPointApartment } from "./apartSourceImg/green-point-apartment";
import { liner } from "./apartSourceImg/liner.js";
import { floraApartment } from "./apartSourceImg/floraApartment";
import { goodVibesOnlyApartment } from "./apartSourceImg/good-vibes-only-apartment";
// import { happyMomentsApartment } from "./apartSourceImg/happy-moments-apartment";
// import { skyRiverApartment } from "./apartSourceImg/sky-river-apartment";
import { centralStreetApartment } from "./apartSourceImg/central-street-apartment";
// import { nаturеApartment } from "./apartSourceImg/nature-apartment";
// import { pinkDrеаmApartment } from "./apartSourceImg/pink-drеаm-араrtmеnt";
import { muzaApаrtment } from "./apartSourceImg/muza-аpаrtment";
import { artPоintApartment } from "./apartSourceImg/art-роint-араrtmеnt";

import { greenApartmentCityViewRecommendations } from "./apartSourceRecommendations/green-apartment-city-view";
import { marshmallowStudioRecommendations } from "./apartSourceRecommendations/marshmallow-studio";
// import { greenPointApartmentRecommendations } from "./apartSourceRecommendations/green-point-apartment";
import { linerRecommendations } from "./apartSourceRecommendations/liner";
import { floraApartmentRecommendations } from "./apartSourceRecommendations/floraApartment";
import { goodVibesOnlyApartmentRecommendations } from "./apartSourceRecommendations/good-vibes-only-apartment";
// import { happyMomentsApartmentRecommendations } from "./apartSourceRecommendations/happy-moments-apartment";
// import { skyRiverApartmentRecommendations } from "./apartSourceRecommendations/sky-river-apartment";
import { centralStreetApartmentRecommendations } from "./apartSourceRecommendations/central-street-apartment";
// import { nаturеApartmentRecommendations } from "./apartSourceRecommendations/nature-apartment";
// import { pinkDrеаmApartmentRecommendations } from "./apartSourceRecommendations/pink-drеаm-араrtmеnt";
import { muzaApаrtmentRecommendations } from "./apartSourceRecommendations/muza-аpаrtment";
import { artPоintApartmentRecommendations } from "./apartSourceRecommendations/art-роint-араrtmеnt";



export const apartmentsPage = [
  // Green apartment city view
  {
    lot: '122233',
    pathname: 'green-apartment-city-view',
    name: 'Green apartment city view',
    amountRoom: 'студия',
    place: '23 м²',
    floor: '14 из 14',
    balcony: 'нет',
    technics: 'кондиционер, холодильник, плита, микроволновка, стиральная машина, водонагреватель, телевизор, фен, утюг',
    communications: 'Wi-Fi, телевидение',
    comfort: 'постельное белье, полотенца, средства гигиены',
    deposit: '3000 ₽',
    amountQuest: '3',
    likeChildren: 'да',
    likeAnimals: 'нет',
    likeSmoke: 'нет',
    likeParty: 'нет',
    accountingDocuments: 'да',
    adress: 'Нижегородская область, Нижний Новгород, ул. Героя Жидкова, 2',
    shortAdress: 'ул. Героя Жидкова, 2, Нижний Новгород',
    shortInfo: 'Квартира-студия, 23 м², 14/14 эт.',
    coordinatesX: 56.301713,
    coordinatesY: 43.982603,
    homeInfo: '14',
    parking: 'на улице, бесплатно для гостей',
  },
  // Marshmallow Studio
  {
    lot: '122231',
    pathname: 'marshmallow-studio',
    name: 'Marshmallow Studio',
    amountRoom: 'студия',
    place: '21 m²',
    floor: '2 из 14',
    balcony: 'нет',
    technics: 'холодильник, плита, микроволновка, стиральная машина, телевизор, фен, утюг',
    communications: 'Wi-Fi, телевидение',
    comfort: 'постельное белье, полотенца, средства гигиены',
    deposit: '3000 ₽',
    amountQuest: '3',
    likeChildren: 'да',
    likeAnimals: 'нет',
    likeSmoke: 'нет',
    likeParty: 'нет',
    accountingDocuments: 'да',
    adress: 'Нижегородская область, Нижний Новгород, Московское ш., 167к3',
    shortAdress: 'Московское шоссе, 167к3, Нижний Новгород',
    shortInfo: 'Квартира-студия, 21 м², 2/14 эт.',
    coordinatesX: 56.315775,
    coordinatesY: 43.890831,
    homeInfo: '14',
    parking: 'на улице, бесплатно для гостей',
  },
  // Green point apartment
  // {
  //   lot: '122229',
  //   pathname: 'green-point-apartment',
  //   name: 'Green point apartment',
  //   amountRoom: '1',
  //   place: '42 м²',
  //   floor: '3 из 25',
  //   balcony: 'балкон',
  //   technics: 'кондиционер, холодильник, плита, микроволновка, стиральная машина, посудомоечная машина, водонагреватель, телевизор, фен, утюг',
  //   communications: 'Wi-Fi, телевидение',
  //   comfort: 'постельное белье, полотенца, средства гигиены',
  //   deposit: '3000 ₽',
  //   amountQuest: '4',
  //   likeChildren: 'да',
  //   likeAnimals: 'нет',
  //   likeSmoke: 'да',
  //   likeParty: 'нет',
  //   accountingDocuments: 'да',
  //   adress: 'Нижегородская область, Нижний Новгород, ул. Тургенева, 25',
  //   shortAdress: 'ул. Тургенева, 25, Нижний Новгород',
  //   shortInfo: '1-к. квартира, 42 м², 3/25 эт.',
  //   coordinatesX: 56.318266,
  //   coordinatesY: 44.039754,
  //   homeInfo: '25',
  //   parking: 'на улице, бесплатно для гостей',
  // },
  // Лайнер
  {
    lot: '122230',
    pathname: 'liner',
    name: 'Лайнер',
    amountRoom: '1',
    place: '40 м²',
    floor: '3 из 11',
    balcony: 'нет',
    technics: 'кондиционер, холодильник, плита, микроволновка, стиральная машина, водонагреватель, телевизор, фен, утюг',
    communications: 'Wi-Fi, телевидение',
    comfort: 'постельное белье, полотенца, средства гигиены',
    deposit: '3000 ₽',
    amountQuest: '4',
    likeChildren: 'да',
    likeAnimals: 'нет',
    likeSmoke: 'нет',
    likeParty: 'нет',
    accountingDocuments: 'да',
    adress: 'Нижегородская область, Нижний Новгород, ул. Максима Горького, 24',
    shortAdress: 'ул. Максима Горького, 24, Нижний Новгород',
    shortInfo: '1-к. квартира, 40 м², 3/11 эт.',
    coordinatesX: 56.310662,
    coordinatesY: 43.980061,
    homeInfo: '11',
    parking: 'на улице, бесплатно для гостей',
  },
  // Flora apartment
  {
    lot: '122241',
    pathname: 'flora-apartment',
    name: 'Flora apartment',
    amountRoom: '2',
    place: '61 м²',
    floor: '3 из 6',
    balcony: 'балкон',
    technics: 'холодильник, плита, микроволновка, стиральная машина, посудомоечная машина, водонагреватель, телевизор, фен, утюг',
    communications: 'Wi-Fi, телевидение',
    comfort: 'постельное белье, полотенца, средства гигиены',
    deposit: '5000 ₽',
    amountQuest: '5',
    likeChildren: 'да',
    likeAnimals: 'нет',
    likeSmoke: 'нет',
    likeParty: 'нет',
    accountingDocuments: 'да',
    adress: 'Нижегородская область, Нижний Новгород, ул. Максима Горького, 45',
    shortAdress: 'ул. Максима Горького, 45, Нижний Новгород',
    shortInfo: '2-к. квартира, 61 м², 3/6 эт.',
    coordinatesX: 56.312345,
    coordinatesY: 43.983672,
    homeInfo: '6',
    parking: 'на улице, бесплатно для гостей',
  },
  // Good vibes only apartment
  {
    lot: '122242',
    pathname: 'good-vibes-only-apartment',
    name: 'Good vibes only apartment',
    amountRoom: 'студия',
    place: '26 м²',
    floor: '7 из 19',
    balcony: 'нет',
    technics: 'кондиционер, холодильник, плита, микроволновка, стиральная машина, водонагреватель, телевизор, фен, утюг',
    communications: 'Wi-Fi, телевидение',
    comfort: 'постельное белье, полотенца, средства гигиены',
    deposit: '3000 ₽',
    amountQuest: '3',
    likeChildren: 'да',
    likeAnimals: 'нет',
    likeSmoke: 'нет',
    likeParty: 'нет',
    accountingDocuments: 'да',
    adress: 'Нижегородская область, Нижний Новгород, ул. Максима Горького, 23А',
    shortAdress: ' ул. Максима Горького, 23А, Нижний Новгород',
    shortInfo: 'Квартира-студия, 26 м², 7/19 эт.',
    coordinatesX: 56.311741,
    coordinatesY: 43.977887,
    homeInfo: '19',
    parking: 'на улице, бесплатно для гостей',
  },
  // Happy moments apartment
  // {
  //   lot: '122244',
  //   pathname: 'happy-moments-apartment',
  //   name: 'Happy moments apartment',
  //   amountRoom: '1',
  //   place: '45 м²',
  //   floor: '4 из 14',
  //   balcony: 'балкон',
  //   technics: 'кондиционер, холодильник, плита, микроволновка, стиральная машина, водонагреватель, телевизор, фен, утюг',
  //   communications: 'Wi-Fi, телевидение',
  //   comfort: 'постельное белье, полотенца, средства гигиены',
  //   deposit: '3000 ₽',
  //   amountQuest: '4',
  //   likeChildren: 'да',
  //   likeAnimals: 'нет',
  //   likeSmoke: 'нет',
  //   likeParty: 'нет',
  //   accountingDocuments: 'да',
  //   adress: 'Нижегородская область, Нижний Новгород, ул. Генкиной, 25А',
  //   shortAdress: 'ул. Генкиной, 25А, Нижний Новгород',
  //   shortInfo: '1-к. квартира, 45 м², 4/14 эт.',
  //   coordinatesX: 56.310632,
  //   coordinatesY: 44.011098,
  //   homeInfo: '14',
  //   parking: 'на улице, бесплатно для гостей',
  // },
  // Sky river apartment
  // {
  //   lot: '122243',
  //   pathname: 'sky-river-apartment',
  //   name: 'Sky river apartment',
  //   amountRoom: '1',
  //   place: '42 м²',
  //   floor: '11 из 17',
  //   balcony: 'балкон',
  //   technics: 'кондиционер, холодильник, плита, микроволновка, стиральная машина, посудомоечная машина, водонагреватель, телевизор, фен, утю',
  //   communications: 'Wi-Fi, телевидение',
  //   comfort: 'постельное белье, полотенца, средства гигиены',
  //   deposit: '3000 ₽',
  //   amountQuest: '4',
  //   likeChildren: 'да',
  //   likeAnimals: 'нет',
  //   likeSmoke: 'нет',
  //   likeParty: 'нет',
  //   accountingDocuments: 'да',
  //   adress: 'Нижегородская область, Нижний Новгород, ул. Родионова, 202/1',
  //   shortAdress: 'ул. Родионова, 202/1, Нижний Новгород',
  //   shortInfo: '1-к. квартира, 42 м², 11/17 эт.',
  //   coordinatesX: 56.299451,
  //   coordinatesY: 44.088389,
  //   homeInfo: '17',
  //   parking: 'на улице, бесплатно для гостей',
  // },
  // Central street apartment
  {
    lot: '122239',
    pathname: 'central-street-apartment',
    name: 'Central street apartment',
    amountRoom: '1',
    place: '42 м²',
    floor: '3 из 6',
    balcony: 'балкон',
    technics: 'кондиционер, холодильник, плита, микроволновка, стиральная машина, посудомоечная машина, водонагреватель, телевизор, фен, утюг',
    communications: 'Wi-Fi, телевидение',
    comfort: 'постельное белье, полотенца, средства гигиены',
    deposit: '3000 ₽',
    amountQuest: '4',
    likeChildren: 'да',
    likeAnimals: 'нет',
    likeSmoke: 'нет',
    likeParty: 'нет',
    accountingDocuments: 'да',
    adress: 'Нижегородская область, Нижний Новгород, ул Большая Покровская, 18А',
    shortAdress: 'ул Большая Покровская, 18А, Нижний Новгород',
    shortInfo: '1-к. квартира, 42 м², 3/6 эт.',
    coordinatesX: 56.322779,
    coordinatesY: 44.002788,
    homeInfo: '6',
    parking: 'на улице, бесплатно для гостей',
  },
  // Nаturе араrtmеnt
  // {
  //   lot: '158315',
  //   pathname: 'nature-apartment',
  //   name: 'Nаturе араrtmеnt',
  //   amountRoom: '1',
  //   place: '38 м²',
  //   floor: '6 из 25',
  //   balcony: 'балкон',
  //   technics: 'кондиционер, холодильник, плита, микроволновка, стиральная машина, водонагреватель, телевизор, фен, утюг',
  //   communications: 'Wi-Fi, телевидение',
  //   comfort: 'постельное белье, полотенца, средства гигиены',
  //   deposit: '3000 ₽',
  //   amountQuest: '4',
  //   likeChildren: 'да',
  //   likeAnimals: 'нет',
  //   likeSmoke: 'нет',
  //   likeParty: 'нет',
  //   accountingDocuments: 'да',
  //   adress: 'Нижегородская область, Нижний Новгород, ул. Тургенева, 25к1',
  //   shortAdress: 'ул. Тургенева, 25к1, Нижний Новгород',
  //   shortInfo: '1-к. квартира, 38 м², 6/25 эт.',
  //   coordinatesX: 56.317537,
  //   coordinatesY: 44.039314,
  //   homeInfo: '25',
  //   parking: 'на улице, бесплатно для гостей',
  // },
  // Рink drеаm араrtmеnt
  // {
  //   lot: '158314',
  //   pathname: 'pink-dream-apartment',
  //   name: 'Рink drеаm араrtmеnt',
  //   amountRoom: '1',
  //   place: '42 м²',
  //   floor: '17 из 19',
  //   balcony: 'балкон',
  //   technics: 'кондиционер, холодильник, плита, микроволновка, стиральная машина, водонагреватель, телевизор, фен, утюг',
  //   communications: 'Wi-Fi, телевидение',
  //   comfort: 'постельное белье, полотенца, средства гигиены',
  //   deposit: '3000 ₽',
  //   amountQuest: '4',
  //   likeChildren: 'да',
  //   likeAnimals: 'нет',
  //   likeSmoke: 'нет',
  //   likeParty: 'нет',
  //   accountingDocuments: 'да',
  //   adress: 'Нижегородская область, Нижний Новгород, ул. Семашко, 28',
  //   shortAdress: 'ул. Семашко, 28, Нижний Новгород',
  //   shortInfo: '1-к. квартира, 42 м², 17/19 эт.',
  //   coordinatesX: 56.321032,
  //   coordinatesY: 44.017934,
  //   homeInfo: '19',
  //   parking: 'на улице, бесплатно для гостей',
  // },
  // Muza аpаrtment
  {
    lot: '149983',
    pathname: 'muza-apartment',
    name: 'Muza аpаrtment',
    amountRoom: 'студия',
    place: '32 м²',
    floor: '17 из 19',
    balcony: 'нет',
    technics: 'холодильник, плита, микроволновка, стиральная машина, телевизор, фен, утюг',
    communications: 'Wi-Fi, телевидение',
    comfort: 'постельное белье, полотенца, средства гигиены',
    deposit: '3000 ₽',
    amountQuest: '4',
    likeChildren: 'да',
    likeAnimals: 'нет',
    likeSmoke: 'нет',
    likeParty: 'нет',
    accountingDocuments: 'да',
    adress: 'Нижегородская область, Нижний Новгород, ул. Максима Горького, 23А',
    shortAdress: 'ул. Максима Горького, 23А, Нижний Новгород',
    shortInfo: 'Квартира-студия, 32 м², 17/19 эт.',
    coordinatesX: 56.311741,
    coordinatesY: 43.977887,
    homeInfo: '19',
    parking: 'на улице, бесплатно для гостей',
  },
  // Аrt роint араrtmеnt
  {
    lot: '136044',
    pathname: 'art-point-apartment',
    name: 'Аrt роint араrtmеnt',
    amountRoom: '1',
    place: '41 м²',
    floor: '11 из 17',
    balcony: 'балкон',
    technics: 'кондиционер, холодильник, плита, микроволновка, стиральная машина, посудомоечная машина, телевизор, фен, утюг',
    communications: 'Wi-Fi, телевидение',
    comfort: 'постельное белье, полотенца, средства гигиены',
    deposit: '3000 ₽',
    amountQuest: '4',
    likeChildren: 'да',
    likeAnimals: 'нет',
    likeSmoke: 'нет',
    likeParty: 'нет',
    accountingDocuments: 'ды',
    adress: 'Нижегородская область, Нижний Новгород, ул. Тимирязева, 7к5',
    shortAdress: 'ул. Тимирязева, 7к5, Нижний Новгород',
    shortInfo: '1-к. квартира, 41 м², 11/17 эт.',
    coordinatesX: 56.305299,
    coordinatesY: 43.999860,
    homeInfo: '17',
    parking: 'на улице, бесплатно для гостей',
  },
];

export const slidesMain = [
  // Green apartment city view
  {
    name: 'Green apartment city view',
    slide: greenApartmentCityViewSlide,
    lot: '122233',
    endpoint: 'green-apartment-city-view',
    price: 'от 2 900 р/сут',
    shortAdress: 'ул. Героя Жидкова, 2, Нижний Новгород',
    shortInfo: 'Квартира-студия, 23м², 14/14 эт.',
    galleryApartSlider: greenApartmentCityView,
    ostrovokru: 'https://ostrovok.ru/hotel/russia/nizhniy_novgorod/mid10437078/',
    sutocnoru: 'https://sutochno.ru/front/searchapp/detail/1030617',
    recommendations: greenApartmentCityViewRecommendations,
  },
  // Marshmallow Studio
  {
    name: 'Marshmallow Studio',
    slide: marshmallowStudioSlide,
    lot: '122231',
    endpoint: 'marshmallow-studio',
    price: 'от 2 500 р/сут',
    shortAdress: 'Московское шоссе, 167к3, Нижний Новгород',
    shortInfo: 'Квартира-студия, 21м², 2/14 эт.',
    galleryApartSlider: marshmallowStudio,
    ostrovokru: 'https://ostrovok.ru/hotel/russia/nizhniy_novgorod/mid10437077/',
    sutocnoru: 'https://sutochno.ru/front/searchapp/detail/1308731',
    recommendations: marshmallowStudioRecommendations,
  },
  // Green point apartment
  // {
  //   name: 'Green point apartment',
  //   slide: greenPointApartmentSlide,
  //   lot: '122229',
  //   endpoint: 'green-point-apartment',
  //   price: 'от 5 000 р/сут',
  //   shortAdress: 'ул. Тургенева, 25, Нижний Новгород',
  //   shortInfo: '1-к. квартира, 42м², 3/25 эт.',
  //   galleryApartSlider: greenPointApartment,
  //   ostrovokru: 'https://ostrovok.ru/hotel/russia/nizhniy_novgorod/mid10437084/',
  //   sutocnoru: 'https://sutochno.ru/front/searchapp/detail/1411611',
  //   recommendations: greenPointApartmentRecommendations,
  // },
  // Лайнер
  {
    name: 'Лайнер',
    slide: linerSlide,
    lot: '122230',
    endpoint: 'liner',
    price: 'от 4 000 р/сут',
    shortAdress: 'ул. Максима Горького, 24, Нижний Новгород',
    shortInfo: '1-к. квартира, 40м², 3/11 эт.',
    galleryApartSlider: liner,
    ostrovokru: 'https://ostrovok.ru/hotel/russia/nizhniy_novgorod/mid10273089/',
    sutocnoru: 'https://sutochno.ru/front/searchapp/detail/1408879',
    recommendations: linerRecommendations,
  },
  // Flora apartment
  {
    name: 'Flora apartment',
    slide: floraApartmentSlide,
    lot: '122241',
    endpoint: 'flora-apartment',
    price: 'от 6 000 р/сут',
    shortAdress: 'ул. Максима Горького, 45, Нижний Новгород',
    shortInfo: '2-к. квартира, 61м², 3/6 эт.',
    galleryApartSlider: floraApartment,
    ostrovokru: 'https://ostrovok.ru/hotel/russia/nizhniy_novgorod/mid10273085/',
    sutocnoru: 'https://sutochno.ru/front/searchapp/detail/1383187',
    recommendations: floraApartmentRecommendations,
  },
  // Good vibes only apartment
  {
    name: 'Good vibes only apartment',
    slide: goodVibesOnlyApartmentSlide,
    lot: '122242',
    endpoint: 'good-vibes-only-apartment',
    price: 'от 3 000 р/сут',
    shortAdress: ' ул. Максима Горького, 23А, Нижний Новгород',
    shortInfo: 'Квартира-студия, 26м², 7/19 эт.',
    galleryApartSlider: goodVibesOnlyApartment,
    ostrovokru: 'https://ostrovok.ru/hotel/russia/nizhniy_novgorod/mid10273086/',
    sutocnoru: 'https://sutochno.ru/front/searchapp/detail/1385827',
    recommendations: goodVibesOnlyApartmentRecommendations,
  },
  // Happy moments apartment
  // {
  //   name: 'Happy moments apartment',
  //   slide: happyMomentsApartmentSlide,
  //   lot: '122244',
  //   endpoint: 'happy-moments-apartment',
  //   price: 'от 4 500 р/сут',
  //   shortAdress: 'ул. Генкиной, 25А, Нижний Новгород',
  //   shortInfo: '1-к. квартира, 45м², 4/14 эт.',
  //   galleryApartSlider: happyMomentsApartment,
  //   ostrovokru: 'https://ostrovok.ru/hotel/russia/nizhniy_novgorod/mid10273086/',
  //   sutocnoru: 'https://sutochno.ru/front/searchapp/detail/1411647',
  //   recommendations: happyMomentsApartmentRecommendations,
  // },
  // Sky river apartment
  // {
  //   name: 'Sky river apartment',
  //   slide: skyRiverApartmentSlide,
  //   lot: '122243',
  //   endpoint: 'sky-river-apartment',
  //   price: 'от 2 900 р/сут',
  //   shortAdress: 'ул. Родионова, 202/1, Нижний Новгород',
  //   shortInfo: '1-к. квартира, 42м², 11/17 эт.',
  //   galleryApartSlider: skyRiverApartment,
  //   ostrovokru: 'https://ostrovok.ru/hotel/russia/nizhniy_novgorod/mid10437086/',
  //   sutocnoru: 'https://sutochno.ru/front/searchapp/detail/1408155',
  //   recommendations: skyRiverApartmentRecommendations,
  // },
  // Central street apartment
  {
    name: 'Central street apartment',
    slide: centralStreetApartmentSlide,
    lot: '122239',
    endpoint: 'central-street-apartment',
    price: 'от 4 000 р/сут',
    shortAdress: 'ул Большая Покровская, 18А, Нижний Новгород',
    shortInfo: '1-к. квартира, 42м², 3/6 эт.',
    galleryApartSlider: centralStreetApartment,
    ostrovokru: 'https://ostrovok.ru/hotel/russia/nizhniy_novgorod/mid10437085/',
    sutocnoru: 'https://sutochno.ru/front/searchapp/detail/1411553',
    recommendations: centralStreetApartmentRecommendations,
  },
  // Nаturе араrtmеnt
  // {
  //   name: 'Nаturе араrtmеnt',
  //   slide: nаturеApartmentSlide,
  //   lot: '158315',
  //   endpoint: 'nature-apartment',
  //   price: 'от 4 000 р/сут',
  //   shortAdress: 'ул. Тургенева, 25к1, Нижний Новгород',
  //   shortInfo: '1-к. квартира, 38м², 6/25 эт.',
  //   galleryApartSlider: nаturеApartment,
  //   ostrovokru: 'https://ostrovok.ru/hotel/russia/nizhniy_novgorod/mid10852823/',
  //   sutocnoru: 'https://sutochno.ru/front/searchapp/detail/1630085',
  //   recommendations: nаturеApartmentRecommendations,
  // },
  // Рink drеаm араrtmеnt
  // {
  //   name: 'Рink drеаm араrtmеnt',
  //   slide: pinkDrеаmApartmentSlide,
  //   lot: '158314',
  //   endpoint: 'pink-dream-apartment',
  //   price: 'от 5 000 р/сут',
  //   shortAdress: 'ул. Семашко, 28, Нижний Новгород',
  //   shortInfo: '1-к. квартира, 42м², 17/19 эт.',
  //   galleryApartSlider: pinkDrеаmApartment,
  //   ostrovokru: 'https://ostrovok.ru/hotel/russia/nizhniy_novgorod/mid10852921/',
  //   sutocnoru: 'https://sutochno.ru/front/searchapp/detail/1630061',
  //   recommendations: pinkDrеаmApartmentRecommendations,
  // },
  // Muza аpаrtment
  {
    name: 'Muza аpаrtment',
    slide: muzaApаrtmentSlide,
    lot: '149983',
    endpoint: 'muza-apartment',
    price: 'от 3 000 р/сут',
    shortAdress: 'ул. Максима Горького, 23А, Нижний Новгород',
    shortInfo: 'Квартира-студия, 32м², 17/19 эт.',
    galleryApartSlider: muzaApаrtment,
    ostrovokru: 'https://ostrovok.ru/hotel/russia/nizhniy_novgorod/mid10677609/',
    sutocnoru: 'https://sutochno.ru/front/searchapp/detail/1592436',
    recommendations: muzaApаrtmentRecommendations,
  },
  // Аrt роint араrtmеnt
  {
    name: 'Аrt роint араrtmеnt',
    slide: artAоintApartmentSlide,
    lot: '136044',
    endpoint: 'art-point-apartment',
    price: 'от 4 000 р/сут',
    shortAdress: 'ул. Тимирязева, 7к5, Нижний Новгород',
    shortInfo: '1-к. квартира, 41м², 11/17 эт.',
    galleryApartSlider: artPоintApartment,
    ostrovokru: 'https://ostrovok.ru/hotel/russia/nizhniy_novgorod/mid10572857/',
    sutocnoru: 'https://sutochno.ru/front/searchapp/detail/1503448',
    recommendations: artPоintApartmentRecommendations,
  },
];
